benchmarks:
  - title: 'MNIST Benchmark 1'
    database_file: 'mnist.db'
    data_set_file: 'datasets/MNIST/train-images-idx3-ubyte'
    # Limit on the data set size
    data_set_limit: 60000
    query_file: 'datasets/MNIST/t10k-images-idx3-ubyte'
    # Limit on the query count
    query_limit: 10000
    data_set_type: 'MNIST'
    top_k: 10
    output_file: 'mnist.json'
    # Number of queries to run per batch
    batch_size: 10000
    params:
      c_search: 2
    index_params:
      c_count: 20
      m: 8
      bits: 4
    version: 'IVFv2'
  - title: 'SIFT Benchmark 1'
    database_file: 'sift.db'
    data_set_file: 'datasets/sift/sift_query.fvecs'
    # Limit on the data set size
    data_set_limit: 10000
    query_file: 'datasets/sift/sift_learn.fvecs'
    # Limit on the query count
    query_limit: 10000
    data_set_type: 'SIFT'
    top_k: 100
    output_file: 'sift.json'
    batch_size: 10000
    params:
      c_search: 2
    index_params:
      c_count: 20
      m: 8
      bits: 4
    version: 'IVFv2'
