benchmarks:
  - title: 'MNIST Benchmark_IVFv2'
    database_file: 'mnist-db-1.pkl'
    data_set_file: 'datasets\\datasets\\MNIST\\train-images-idx3-ubyte'
    # Limit on the data set size
    data_set_limit: 60000
    query_file: 'datasets\\datasets\\MNIST\\t10k-images-idx3-ubyte'
    # Limit on the query count
    query_limit: 10000
    data_set_type: 'MNIST'
    top_k: 10
    output_file: 'mnist-results_IVFv2.pkl'
    # Number of queries to run per batch
    batch_size: 8
    params:
      c_search: 2
    index_params:
      c_count: 20
      m: 8
      bits: 4
    version: 'IVFv2'
  - title: 'MNIST Benchmark_IVF'
    database_file: 'mnist-db-1.pkl'
    data_set_file: 'datasets\\datasets\\MNIST\\train-images-idx3-ubyte'
    # Limit on the data set size
    data_set_limit: 60000
    query_file: 'datasets\\datasets\\MNIST\\t10k-images-idx3-ubyte'
    # Limit on the query count
    query_limit: 10000
    data_set_type: 'MNIST'
    top_k: 10
    output_file: 'mnist-results_IVF.pkl'
    # Number of queries to run per batch
    batch_size: 8
    params:
      c_search: 2
    index_params:
      c_count: 20
    version: 'IVF'
  - title: 'SIFT Benchmark_IVFv2'
    database_file: 'sift-db-1.pkl'
    data_set_file: 'datasets\\datasets\\sift\\sift_base.fvecs'
    # Limit on the data set size
    # data_set_limit: 1000000
    data_set_limit: 100000
    # data_set_limit: 10000
    query_file: 'datasets\\datasets\\sift\\sift_learn.fvecs'
    # Limit on the query count
    query_limit: 1000
    data_set_type: 'SIFT'
    top_k: 10
    output_file: 'sift-results_IVFv2.pkl'
    batch_size: 8
    params:
      c_search: 2
    index_params:
      c_count: 20
      m: 8
      bits: 4
    version: 'IVFv2'
  - title: 'SIFT Benchmark_IVF'
    database_file: 'sift-db-1.pkl'
    data_set_file: 'datasets\\datasets\\sift\\sift_base.fvecs'
    # Limit on the data set size
    # data_set_limit: 1000000
    data_set_limit: 100000
    # data_set_limit: 10000
    query_file: 'datasets\\datasets\\sift\\sift_learn.fvecs'
    # Limit on the query count
    query_limit: 1000
    data_set_type: 'SIFT'
    top_k: 10
    output_file: 'sift-results_IVF.pkl'
    batch_size: 8
    params:
      c_search: 2
    index_params:
      c_count: 20
    version: 'IVF'
